BookmarkConstants = {
  BOOKMARK_RECEIVED: "BOOKMARK RECEIVED",
  BOOKMARKS_RECEIVED: "BOOKMARKS RECEIVED",
  REMOVE_BOOKMARK: "REMOVE BOOKMARK",
  CLEAR_BOOKMARKS: "CLEAR BOOKMARKS"
}

module.exports = BookmarkConstants
