# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)



User.create!([
  {username: "DemoUser", password: "password"}
  ])

Event.create!([
  {title: "Designers + Geeks: Life x Design" ,location: "140 New Montgomery St San Francisco, CA 94105" ,category: "Science & Tech" ,description: "The 40-hour work week is dead. So is the suburban dream of a house with a yard, fence, and two-car garage. People increasingly live in the city, change jobs every few years, and seek to minimize possessions. And not just young people - these changes are happening across age groups and around the world. Entrepreneurs are rethinking the fundamentals of how we live, optimizing them for a future full of digital nomads and a growing middle class. This session of Designers + Geeks will look at the evolution of careers, working environments, and living situations. With speakers from some of the companies leading this evolution, we'll look at what the future holds for modern living. Have something to share at Life X Design? Fill out our call for content and we'll get in touch if we can fit you in at the event.", picture_url:"http://res.cloudinary.com/du8uwloft/image/upload/v1470429013/dxfrn5l3fwdk5csf5wx0.png", price: 10 , start_date: "Wed, 10 Aug 2017", end_date:"Wed, 10 Aug 2017" ,start_time: "2000-01-01 01:00:00 UTC", end_time: "2000-01-01 02:02:00 UTC", user_id: 1 , lat:37.786964, lng:-122.399883},
  {title: "San Francisco Comic Con",location: "Marriott Marquis - 780 Mission Street, San Francisco, CA 94103" ,category: "hobbies" ,picture_url: "http://res.cloudinary.com/du8uwloft/image/upload/v1470431773/comic_con_u8fpn1.jpg",price: 10, start_date: "Mon, 11 Sept 2017", end_date: "Mon, 11 Sept 2017", start_time: "2000-01-01 16:00:00 UTC", end_time: "2000-01-01 20:00:00 UTC", user_id: 1 ,lat:37.785482, lng: -122.404421, description: "Imaginarium is a multi-faceted event production and advertising agency. Based in Central Florida, we produce and promote comic conventions in select cities throughout the United States and provide advertising services to clients worldwide. The founders of Imaginarium are full-fledged comic book and comic book original art nerds."},
  {title: "Eat Drink SF 2017" ,location: "2 Marina Boulevard San Francisco, CA 94109", category: "Food & Drink", price: 5, start_date: "Mon, 11 Dec 2017", end_date: "Mon, 11 Dec 2017", start_time: "2000-01-01 12:00:00 UTC", end_time: "2000-01-01 15:00:00 UTC", user_id: 1, lat: 37.807071,lng: -122.431807, picture_url:"http://res.cloudinary.com/du8uwloft/image/upload/v1470432953/eat_drink_sf_kya41p.jpg", description: "San Francisco's premier food, wine, beer, and spirits festival. Eat Drink SF (fka SF Chefs) returns for its 8th year to celebrate the Bay Area's world-class culinary community. The festival is four days of delicious events featuring our signature Grand Tasting experiences that highlight 160+ restaurants and 70+ breweries, wineries and distilleries throughout the weekend. Guests meet the areas top chefs, taste their way through more than 35 creative bites from restaurants around the Bay Area (four Grand Tastings each feature different restaurants), enjoy unlimited pours of wine, beer and cocktails, learn about wine in the SF Wine School's classroom, watch demonstrations on the main stage, and be part of this quintessentially San Francisco celebration of flavor. Your ticket includes everything, no wallet is needed inside."},
  {title: "Charity Fashion Show 2017 #DF17" ,location: "302 Powell Street San Francisco, CA 94102", category: "fashion", price: 1, start_date: "Thur, 12 Oct 2017", end_date: "Thur, 12 Oct 2017", start_time: "2000-01-01 17:00:00 UTC", end_time: "2000-01-01 21:00:00 UTC", user_id: 1, lat: 37.787648, lng: -122.408279, picture_url: "http://res.cloudinary.com/du8uwloft/image/upload/v1470433353/fashion_show_ol0gy8.jpg", description: "Event Description Britex Fabrics presents: PROJKT Maiden Lane A Fall Fashion Show Featuring: Emily Payne, presenting her children's line Devon Rose and introducing her new unisex outerwear collection, Richard Hallmarq, Kini Zamora (Project runway) and Rey Ortiz (Under the Gunn) With San Francisco ARTist: Michael Covington (collaborative pieces with Emily Payne) Custom Masks Designed by L.V.M. and DJ Keith Kraft"},
  {title: "Summer Breeze Half Marathon/10K/5K, August 6th, 2017", location: "14001 Monarch Bay Drive San Leandro, CA 94577", category: "Sports & Fitness", price: 10, start_date: "Sun, 6 Aug 2017", end_date: "Sun, 6 Aug 2017", start_time: "2000-01-01 13:00:00 UTC", end_time: "2000-01-01 18:00:00 UTC", user_id: 1, lat:37.695825, lng:-122.186192, picture_url: "http://res.cloudinary.com/du8uwloft/image/upload/v1470433672/half_marathon_hsgapo.jpg", description: "All race distances start and finish at the San Leandro Marina Park! Whether you are a frequent race winner or a first-time runner/walker, you've got a lot to look forward to. All participants will enjoy a mostly-flat, easy bayside trail that rarely strays more than a few feet from water. The absence of hills makes these courses perfect for those looking to set a personal record as well as those those participating in their first race or first attempt at a longer distance! Hikers/walkers are always welcome All runners will receive custom finisher medals and custom shirts (cotton and tech shirts available). More info on shirts/awards page. Age group awards will be awarded to the top 3 finishers in 5 year categories (less for the younger ages)."},
  {title: "Japanese Tea Garden Co-Curricular", location: "75 Hagiwara Tea Garden Drive, San Francisco, CA 94102", category: "Travel & Outdoor", price: 1, start_date: "Sun, 24 Sept 2017",end_date: "Sun, 24 Sept 2017", start_time: "2000-01-01 12:00:00 UTC", end_time: "2000-01-01 15:00:00 UTC", user_id: 1, lat: 37.770684,lng: -122.470215, picture_url: "http://res.cloudinary.com/du8uwloft/image/upload/v1470433925/travel_outdoor_pkn2ak.jpg", description: "During this Co-Curricular you will be able to explore one of the most iconic gardens in San Francisco, the garden where history meets nature. The Japanese Tea Garden is not only the physical representation of Japanese cultural influence on the city but  is also the embodiment of the effort to preserve and incorporate nature in the lives of citizens. In the Garden, not only will you be able to find several wooden bridges, koi ponds and pagodas, but you will also be able to relax in zen gardens surrounded by Japanese azaleas and bonsai trees. You will be given the task to find a fairy door (info here) while you explore the garden and its surroundings.  Also, as a souvenir (also known as an “artifact”) you will be able to take a fortune cookie from the place where these were first served! ! In the same tea shop you can have traditional japanese refreshments and snacks. As another available option, you will be able to pay a visit to the DeYoung Observation Deck at the Hamon Tower to take some incredible pictures of  Golden Gate Park.  At the end of the adventure, on the way back to the residence you will take a little detour to see the Tiled Steps, one of the most famous sightseeing spots in San Francisco."},
  {title: "ArtSpan's Artist Workshop: The Inner & Outer Game of Selling Your Art", location: "934 Brannan Street San Francisco, CA 94103", category: "Art", price: 5, start_date: "Wed, 20 Sept 2017", end_date: "Wed, 20 Sept 2017", start_time: "2000-01-01 10:00:00 UTC", end_time: "2000-01-01 14:00:00 UTC", user_id: 1, lat: 37.771353, lng: -122.406567, picture_url: "http://res.cloudinary.com/du8uwloft/image/upload/v1469517068/uk7xcfif1pp0rk6qp0gx.jpg", description: "THE INNER & OUTER GAME OF SELLING YOUR ART Is it hard for you to sell your art?  Do you think that being a good sales person requires you to be pushy or manipulative? Are you confused about what to do or say when someone walks into your studio to look at your work? Do you frequently wonder how the art sales process works and how to do it right? If you answered YES to any of these questions then this workshop is for you! Many artists find the sales process difficult and daunting and most do not take the time to learn how to sell. It’s easier to stick to the belief that the art will sell itself or resign to the idea that that you simply do not have the personality to be a good sales person. If more artists took the time to learn about selling, they would sell more art, be more successful with their art businesses and actually enjoy selling and getting to know buyers and collectors. What a novel idea! In this 2-hour workshop you will learn:" },
  {title: "THE 5th ANNUAL FREE HALLOWEEN PARTY w/ BRODINSKI & MORE at 1015 FOLSOM", location: "1015 Folsom San Francisco, CA", category: "Music", price: 20, start_date: "Fri, 20 Oct 2017",end_date: "Sat, 21 Oct 2017", start_time: "2000-01-01 22:00:00 UTC", end_time: "2000-01-01 04:00:00 UTC", user_id: 1, lat: 37.778377, lng: -122.405752, picture_url: "http://res.cloudinary.com/du8uwloft/image/upload/v1470434517/music_utljhm.jpg", description: "Love is in the air when Brodinski starts talking about music. Making music, playing music, sharing music, finding music, promoting music… it’s all about L-U-V, as The Shangri-La’s used to say. Ever since young Louis Rogé decided to flunk university and turn Brodinksi into a full time operation, it was his passion for unearthing and creating exciting new tunes that drove him forward. No surprise then, when Brodi unveils his newest enterprise, it turns out to be another amorously inspired scheme: the aptly named Bromance is a music label devoted ‘people we love’, according to its main creator and A&R man. Brodinski: “I’ve always loved collaborating with other people, ‘cause I get bored too easily. When working together, my head gets fed all the time, new ideas come flying from all directions. The more projects I’m involved in, the better! With Bromance I’m taking that feeling to the next level”." },
  {title: "New York Career Fair", location: "440 West 57th Street New York, NY 10019 ", category: "Business", price: 2, start_date: "Sun, 20 Aug 2017", end_date: "Sun, 20 Aug 2017", start_time: "2000-01-01 12:00:00 UTC", end_time: "2000-01-01 16:00:00 UTC", user_id: 1, lat: 40.768469,lng: -73.987426, picture_url: "http://res.cloudinary.com/du8uwloft/image/upload/v1470434733/business_NY_ozyb2i.png", description: "On Thursday, August 11th, 2016, Best Hire Career Fairs will be hosting a huge live hiring event in New York, New York. You will get your chance to meet the hiring decision makers from the area's best employers in New York. You should attend the career fair; there will be hundreds of jobs available. All you need to do is dress professionally and bring lots of resumes to the job fair. Just walk in the event and start interviewing, it's that easy. It saves you energy, money and time, you can just stick to one location where you will get a chance to interview with multiple companies. The companies offer several openings and are anxious to meet you. You just need to be at the event and be the one to impress the decision makers."}
  ])

Bookmark.create!([
  {user_id: 1,bookmark_id: 1},
  {user_id: 1,bookmark_id: 3},
  {user_id: 1,bookmark_id: 7}
  ])

Relationship.create!([
  {show_id: 1,purchaser_id: 1}
  ])
